### ISSUE TITLE
Item seperator for the recycler view

### ISSUE THREAD

**Issue by vijaysaimutyala** [DarkJaguar91/DJDecor#1]
thanks to the wonderful library u have created. I wanted to add an item seperator between the recycler view items. I have seen that u have a class that extends the Item Decoration. How do I make use of it to create a seperator?

**Comment by DarkJaguar91** [comment]
Hi,

Sorry for such a late reply. 

By separator do you mean a blank space, or some sort of line/image between each item?

If its just white space I would suggest you create your own Decoration rather than use this library:

```
public class MyDecoration extends RecyclerView.ItemDecoration {
   @Override
   public void getItemOffsets(Rect outRect, View view, RecyclerView parent, RecyclerView.State state){
      super.getItemOffsets(outRect, view, parent, state);
      outRect.top = 10; // or whatever size space you want between your elements `
   }
}
```

Then add it to your recyclerView as follows:
`recyclerView..addItemDecoration(new MyDecoration());`

Otherwise if you want to add view elements such as a line or image.
First define your layout of the separator: my_separator.xml
Then use my library as defined but make your adapter override methods as follows:

```
   @Override
    public long getHeaderId(int position) {
        return position;
    }

    @Override
    public ViewHolder onCreateHeaderViewHolder(ViewGroup parent) {
        return new ViewHolder(LayoutInflater.from(parent.getContext()).inflate(R.layout.my_separator, parent, false));
    }

    @Override
    public void onBindHeaderViewHolder(ViewHolder viewHolder, int postion) {
    }
```

**Comment by vijaysaimutyala** [comment]
Thank you Brandon !!
